name: Actualizar Supabase

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  actualizar:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar JSON de OneDrive
        run: |
          curl -L "https://adslhouse-my.sharepoint.com/:u:/p/efarfan/IQCusPJ4g4fFT7AzRybfEWxjAZHeeW0cU6-ZcYxhQUh-T4k?e=Pruk5G&download=1" -o datos.json
          cat datos.json

      - name: Verificar secret
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          echo "KEY length: ${#SUPABASE_KEY}"

      - name: Vaciar tabla en Supabase
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        run: |
          curl -X DELETE "${SUPABASE_URL}/rest/v1/registros?id=gte.0" \
            -H "apikey: ${SUPABASE_KEY}" \
            -H "Authorization: Bearer ${SUPABASE_KEY}" \
            -H "Content-Type: application/json" \
            -H "Prefer: return=minimal"

      - name: Insertar datos en Supabase
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        run: |
          curl -X POST "${SUPABASE_URL}/rest/v1/registros" \
            -H "apikey: ${SUPABASE_KEY}" \
            -H "Authorization: Bearer ${SUPABASE_KEY}" \
            -H "Content-Type: application/json" \
            -H "Prefer: return=minimal" \
            -d @datos.json
