name: Actualizar Supabase

on:
  repository_dispatch:
    types: [actualizar-datos]
  workflow_dispatch:

jobs:
  actualizar:
    runs-on: ubuntu-latest
    steps:
      - name: Guardar JSON
        run: |
          echo '${{ toJson(github.event.client_payload) }}' > datos.json
          cat datos.json

      - name: Vaciar tabla en Supabase
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        run: |
          curl -X DELETE "${SUPABASE_URL}/rest/v1/registros?id=gte.0" \
            -H "apikey: ${SUPABASE_KEY}" \
            -H "Authorization: Bearer ${SUPABASE_KEY}" \
            -H "Content-Type: application/json" \
            -H "Prefer: return=minimal"

      - name: Insertar datos en Supabase
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        run: |
          curl -X POST "${SUPABASE_URL}/rest/v1/registros" \
            -H "apikey: ${SUPABASE_KEY}" \
            -H "Authorization: Bearer ${SUPABASE_KEY}" \
            -H "Content-Type: application/json" \
            -H "Prefer: return=minimal" \
            -d @datos.json
