name: Actualizar Supabase

on:
  schedule:
    - cron: '0 * * * *'  # cada hora
  workflow_dispatch:  # permite ejecutarlo manualmente

jobs:
  actualizar:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar JSON de OneDrive
        run: |
          curl -L "https://adslhouse-my.sharepoint.com/personal/efarfan_adslhouse_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fefarfan%5Fadslhouse%5Fcom%2FDocuments%2FDocumentos%2FPruebas%20reporte%20col%2Fdatos%2Ejson&parent=%2Fpersonal%2Fefarfan%5Fadslhouse%5Fcom%2FDocuments%2FDocumentos%2FPruebas%20reporte%20col&ga=1" -o datos.json
          cat datos.json

      - name: Vaciar tabla en Supabase
        run: |
          curl -X DELETE "https://edcnjdupwvjxutlaemdy.supabase.co/rest/v1/registros?id=gte.0" \
            -H "apikey: ${{ secrets.SUPABASE_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_KEY }}" \
            -H "Content-Type: application/json" \
            -H "Prefer: return=minimal"

      - name: Insertar datos en Supabase
        run: |
          curl -X POST "https://edcnjdupwvjxutlaemdy.supabase.co/rest/v1/registros" \
            -H "apikey: ${{ secrets.SUPABASE_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_KEY }}" \
            -H "Content-Type: application/json" \
            -H "Prefer: return=minimal" \
            -d @datos.json
